-- MySQL Script generated by MySQL Workbench
-- ter 04 jun 2024 11:52:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_partiu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_partiu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_partiu` DEFAULT CHARACTER SET utf8 ;
USE `db_partiu` ;

-- -----------------------------------------------------
-- Table `db_partiu`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_partiu`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`estado` (
  `codEstado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_partiu`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`cidade` (
  `codCidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `populacao` INT NOT NULL,
  `descricao` TEXT NOT NULL,
  `estado_codEstado` INT NOT NULL,
  PRIMARY KEY (`codCidade`, `estado_codEstado`),
  INDEX `fk_cidade_estado1_idx` (`estado_codEstado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_codEstado`)
    REFERENCES `db_partiu`.`estado` (`codEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_partiu`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`hotel` (
  `codHotel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `numQuartos` INT NOT NULL,
  `categoria` INT(10) NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `cidade_codCidade` INT NOT NULL,
  PRIMARY KEY (`codHotel`, `cidade_codCidade`),
  INDEX `fk_hotel_cidade1_idx` (`cidade_codCidade` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_cidade1`
    FOREIGN KEY (`cidade_codCidade`)
    REFERENCES `db_partiu`.`cidade` (`codCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_partiu`.`pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`pacote` (
  `codPacote` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(7,2) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  `cidade_codCidade` INT NOT NULL,
  `hotel_codHotel` INT NOT NULL,
  PRIMARY KEY (`codPacote`, `cidade_codCidade`, `hotel_codHotel`),
  INDEX `fk_pacote_cidade1_idx` (`cidade_codCidade` ASC) VISIBLE,
  INDEX `fk_pacote_hotel1_idx` (`hotel_codHotel` ASC) VISIBLE,
  CONSTRAINT `fk_pacote_cidade1`
    FOREIGN KEY (`cidade_codCidade`)
    REFERENCES `db_partiu`.`cidade` (`codCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacote_hotel1`
    FOREIGN KEY (`hotel_codHotel`)
    REFERENCES `db_partiu`.`hotel` (`codHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_partiu`.`pontoTuristico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`pontoTuristico` (
  `codPontoTuristico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `cidade_codCidade` INT NOT NULL,
  PRIMARY KEY (`codPontoTuristico`, `cidade_codCidade`),
  INDEX `fk_pontoTuristico_cidade1_idx` (`cidade_codCidade` ASC) VISIBLE,
  CONSTRAINT `fk_pontoTuristico_cidade1`
    FOREIGN KEY (`cidade_codCidade`)
    REFERENCES `db_partiu`.`cidade` (`codCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_partiu`.`cliente_has_pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`cliente_has_pacote` (
  `cliente_codCliente` INT NOT NULL,
  `pacote_codPacote` INT NOT NULL,
  PRIMARY KEY (`cliente_codCliente`, `pacote_codPacote`),
  INDEX `fk_cliente_has_pacote_pacote1_idx` (`pacote_codPacote` ASC) VISIBLE,
  INDEX `fk_cliente_has_pacote_cliente_idx` (`cliente_codCliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_pacote_cliente`
    FOREIGN KEY (`cliente_codCliente`)
    REFERENCES `db_partiu`.`cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_pacote_pacote1`
    FOREIGN KEY (`pacote_codPacote`)
    REFERENCES `db_partiu`.`pacote` (`codPacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_partiu`.`pacote_has_pontoTuristico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_partiu`.`pacote_has_pontoTuristico` (
  `pacote_codPacote` INT NOT NULL,
  `pontoTuristico_codPontoTuristico` INT NOT NULL,
  `dia` DATE NOT NULL,
  `horaInical` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  PRIMARY KEY (`pacote_codPacote`, `pontoTuristico_codPontoTuristico`),
  INDEX `fk_pacote_has_pontoTuristico_pontoTuristico1_idx` (`pontoTuristico_codPontoTuristico` ASC) VISIBLE,
  INDEX `fk_pacote_has_pontoTuristico_pacote1_idx` (`pacote_codPacote` ASC) VISIBLE,
  CONSTRAINT `fk_pacote_has_pontoTuristico_pacote1`
    FOREIGN KEY (`pacote_codPacote`)
    REFERENCES `db_partiu`.`pacote` (`codPacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacote_has_pontoTuristico_pontoTuristico1`
    FOREIGN KEY (`pontoTuristico_codPontoTuristico`)
    REFERENCES `db_partiu`.`pontoTuristico` (`codPontoTuristico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
